[package]
name = "docserver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.68"
bytes = "1.3.0"
clap = { version = "4.5.51", features = ["derive"] }
indexmap = "2.11.4"
thiserror = "1.0.38"
urlencoding = "2.1.3"
